### ISSUE TITLE
Getting an error on MacOs 15

### ISSUE THREAD

**Issue by wwhtrbbtt** [vbaicu/mMusicCast#21]

**Comment by wwhtrbbtt** [comment]
Uncaught Exception:
Error: Unexpected server response: 404
    at ClientRequest._req.on (/Users/peter/Desktop/scrpy-with-audio/mMusicCast-master/node_modules/ws/lib/websocket.js:641:21)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
