### ISSUE TITLE
failed to install on raspberry pi raspbian stretch 4.4

### ISSUE THREAD

**Issue by kiai72** [vbaicu/mMusicCast#9]
install + start on windows worked - but i want to have this on raspberry pi.
it failed - see log further down.
i just did:
- sudo apt-get install nodejs
- sudo apt-get install npm
- npm install

what's wrong ?

pi@retropie:~/mmusiccast $ npm install
(node:17746) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json mMusicCast@1.1.0 No repository field.
npm WARN package.json mMusicCast@1.1.0 No license field.
npm WARN package.json optimist@0.6.1 license should be a valid SPDX license expression
npm WARN package.json peer-ssdp@0.0.5 No license field.
npm WARN package.json querystring@0.2.0 querystring is also the name of a node core module.
npm WARN package.json querystring@0.2.0 No license field.
npm WARN package.json node-uuid@1.4.8 No license field.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.72v7-aufs
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/mmusiccast
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/mmusiccast/npm-debug.log
npm ERR! not ok code 0
pi@retropie:~/mmusiccast $

pi@retropie:~/mmusiccast $ npm version
(node:18046) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
{ http_parser: '2.8.1',
  node: '8.11.1',
  v8: '6.2.414.50',
  uv: '1.18.0',
  zlib: '1.2.8',
  ares: '1.14.0',
  modules: '57',
  nghttp2: '1.25.0',
  openssl: '1.0.2l',
  icu: '57.1',
  unicode: '8.0',
  cldr: '29.0',
  tz: '2016b',
  npm: '1.4.21',
  mMusicCast: '1.1.0' }
pi@retropie:~/mmusiccast $

**Comment by vbaicu** [comment]
Hi,
Yes, you need the x11 in order to run it. Application runs with electron which requires it. If you attempt to run it via ssh it won't work unless you export the display variable first.

`export DISPLAY:=0`
